version: "3"

services:
  web:
    build: .
    command: gunicorn i2dbackend.wsgi --bind 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./:/project
    networks:
      - backend
      
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./i2dbackend/static:/project/static
    environment:
      DJANGO_WEB_HOST: "web"
    networks:
      - backend
    depends_on:
      - web

networks:
  backend:
    driver: bridge