def descargarzip(request):
    # ...existing code...
    nombre = request.GET.get('nombre', 'descarga_datos')
    # ...existing code...
    response = HttpResponse(zip_buffer, content_type='application/zip')
    response['Content-Disposition'] = f'attachment; filename={nombre}.zip'
    return response
# ...existing code...