# Generated by Django 3.1.7 on 2021-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mupio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpioPolitico',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('dpto_ccdgo', models.CharField(blank=True, max_length=2, null=True)),
                ('mpio_ccdgo', models.CharField(blank=True, max_length=3, null=True)),
                ('mpio_cnmbr', models.CharField(blank=True, max_length=60, null=True)),
                ('mpio_crslc', models.CharField(blank=True, max_length=60, null=True)),
                ('mpio_narea', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mpio_ccnct', models.CharField(blank=True, max_length=5, null=True)),
                ('mpio_nano', models.BigIntegerField(blank=True, null=True)),
                ('dpto_cnmbr', models.CharField(blank=True, max_length=250, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_len', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('orig_fid', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mpio_politico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MpioTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpio_ccnct', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('mpio_cnmbr', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'mpio_tipo',
                'managed': False,
            },
        ),
    ]
