# Generated by Django 3.1.7 on 2021-04-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mupio', '0002_mpiopolitico_mpiotipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpioPolitico',
        ),
    ]
