# Generated by Django 3.1.7 on 2021-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mupio', '0003_delete_mpiopolitico'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpioAmenazas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('amenazadas', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'mpio_amenazas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MpioQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('registers', models.BigIntegerField(blank=True, null=True)),
                ('species', models.BigIntegerField(blank=True, null=True)),
                ('exoticas', models.BigIntegerField(blank=True, null=True)),
                ('endemicas', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'mpio_queries',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MpioTipo',
        ),
    ]
