# Generated by Django 3.1.7 on 2021-04-08 19:01

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension(name='unaccent'),
    ]
