# Generated by Django 3.1.7 on 2021-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mupio', '0002_auto_20210226_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpioTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpio_ccnct', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('mpio_cnmbr', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'mpio_tipo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='mpio_tipo',
        ),
    ]
