# Generated by Django 3.1.7 on 2025-08-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(help_text='Short name for URL access', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Full project name', max_length=200)),
                ('logo_pequeno_url', models.URLField(blank=True, help_text='Small logo URL', null=True)),
                ('logo_completo_url', models.URLField(blank=True, help_text='Complete logo URL', null=True)),
                ('nivel_zoom', models.FloatField(default=6.0, help_text='Default zoom level')),
                ('coordenada_central_x', models.FloatField(help_text='Center X coordinate')),
                ('coordenada_central_y', models.FloatField(help_text='Center Y coordinate')),
                ('panel_visible', models.BooleanField(default=True, help_text='Panel visibility on startup')),
                ('base_map_visible', models.CharField(choices=[('streetmap', 'Street Map'), ('cartodb_positron', 'CartoDB Positron'), ('otm', 'OpenTopoMap'), ('bw', 'Black & White'), ('terrain', 'Terrain'), ('esri_physical', 'Esri World Physical'), ('esri_imagery', 'Esri World Imagery')], default='streetmap', help_text='Default visible base map', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Group name', max_length=200)),
                ('orden', models.IntegerField(default=0, help_text='Display order')),
                ('fold_state', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', help_text='Initial fold state', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_group', models.ForeignKey(blank=True, help_text='Parent group for subgroups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='projects.layergroup')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='projects.project')),
            ],
            options={
                'verbose_name': 'Layer Group',
                'verbose_name_plural': 'Layer Groups',
                'db_table': 'layer_groups',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_geoserver', models.CharField(help_text='GeoServer layer name', max_length=200)),
                ('nombre_display', models.CharField(help_text='Display name in frontend', max_length=200)),
                ('store_geoserver', models.CharField(help_text='GeoServer store name', max_length=200)),
                ('estado_inicial', models.BooleanField(default=False, help_text='Initial visibility state')),
                ('metadata_id', models.CharField(blank=True, help_text='Metadata ID or external URL', max_length=500, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Display order within group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='projects.layergroup')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'db_table': 'layers',
                'ordering': ['orden', 'nombre_display'],
            },
        ),
        migrations.CreateModel(
            name='DefaultLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_inicial', models.BooleanField(default=True, help_text='Initial visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.layer')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_layers', to='projects.project')),
            ],
            options={
                'verbose_name': 'Default Layer',
                'verbose_name_plural': 'Default Layers',
                'db_table': 'default_layers',
                'unique_together': {('proyecto', 'layer')},
            },
        ),
    ]
