# Generated by Django 4.2.30 on 2026-06-10 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_layergroup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='metadata_selector',
            field=models.CharField(choices=[('geografico', 'Geográfico'), ('biologico', 'Biológico'), ('biocultural', 'Biocultural'), ('externo', 'Externo')], default='geografico', help_text='Metadata catalog', max_length=100),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='color',
            field=models.CharField(default='#eeeeee', help_text='Hexadecimal color code for the layer group (e.g., #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Enter a valid hexadecimal color code (e.g., #FF5733 or #F57)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_map_visible',
            field=models.CharField(choices=[('streetmap', 'OpenStreetMap'), ('cartodb_positron', 'CartoDB Positron'), ('otm', 'OpenTopoMap'), ('bw', 'Black & White'), ('terrain', 'Terrain'), ('esri_physical', 'Esri World Physical'), ('esri_imagery', 'Esri World Imagery')], default='streetmap', help_text='Default visible base map', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DefaultLayer',
        ),
    ]
