# Generated by Django 4.2.30 on 2026-07-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_layer_metadata_selector_alter_layer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extent',
            field=models.CharField(default='-7430902, -479413, -8795762, 1408887', help_text='Extent of project', max_length=200),
        ),
    ]
